        } catch (\Throwable $e) {
            report($e);
            abort(500, $e->getMessage());
        }
        
        
        
@extends('errors::layout')

@section('title', __('Server Error'))
@section('content')
<div class="error-page">
  <h2 class="headline text-red">500</h2>
  <div class="error-content">
    <h3>
      <i class="fa fa-exclamation-triangle text-red"></i>
      サーバ内部のエラー
    </h3>
    @if (!empty($exception->getMessage()))
      <p class="alert alert-danger mt-4">{{ $exception->getMessage() }}</p>
    @endif
    <p>
      申し訳ございませんが、システム管理者にお問い合わせいただくか、復旧をお待ちください。
      <a href="{{ route('login') }}">こちら</a>からホームに戻ることができます。
    </p>
  </div>
</div>
@endsection